services:
  why_is_docker_the_best:
    image: ghcr.io/akasiek/why_is_docker_the_best:latest
    restart: unless-stopped
    ports:
      - "8080:8080"

    # If mounting data volume as a path on the host, ensure it has appropriate permissions for the container user.
    user: "${UID:-1000}:${GID:-1000}"

    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL # Drop all Linux capabilities. The application doesn't need any special permissions.
